POST http://localhost:8080/publish
Content-Type: application/json

{
  "topicName": "my-topic",
  "message": "Hello Kafka"
}

### Publish sample message for word count stream
POST http://localhost:8080/publish
Content-Type: application/json

{
    "topicName": "wordcount-input",
    "message": "안녕하세요 tree"
}