POST http://localhost:8080/publish
Content-Type: application/json

{
  "topicName": "wordcount-output",
  "message": "Hello Kafka"
}

### Publish sample message for word count stream
POST http://localhost:8080/publish
Content-Type: application/json

{
    "topicName": "wordcount-input",
    "message": "my father is jang hyunsik"
}